gText_Birch_Welcome::
	.string "Hello welcome to pokemon bubber epic\n"
	.string "special demo TWO\p"
	.string "$"
	@ .string "Hi! Sorry to keep you waiting!\p"
	@ .string "Welcome to the world of POKéMON!\p"
	@ .string "My name is BIRCH.\p"
	@ .string "But everyone calls me the POKéMON\n"
	@ .string "PROFESSOR.\p"
	@ .string "$"

gText_Birch_Pokemon::
	@ .string "This is what we call a “POKéMON.”\p"
	.string "Take a look at this fucking duck\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Domohead: hello it is i, the bastard\n"
	.string "now trying to stop you\p"
	.string "yeah i'm not gonna let you climb that\n"
	.string "tower even though i have no incentive\l"
	.string "not to just let you\p"
	.string "Now you must face my elite team of\n"
	.string "definitely all ducks.\p"
	.string "$"
	@ .string "This world is widely inhabited by\n"
	@ .string "creatures known as POKéMON.\p"
	@ .string "We humans live alongside POKéMON,\n"
	@ .string "at times as friendly playmates, and\l"
	@ .string "at times as cooperative workmates.\p"
	@ .string "And sometimes, we band together\n"
	@ .string "and battle others like us.\p"
	@ .string "But despite our closeness, we don't\n"
	@ .string "know everything about POKéMON.\p"
	@ .string "In fact, there are many, many\n"
	@ .string "secrets surrounding POKéMON.\p"
	@ .string "To unravel POKéMON mysteries,\n"
	@ .string "I've been undertaking research.\l"
	@ .string "That's what I do.\p"
	@ .string "$"

gText_Birch_AndYouAre::
	@ .string "And you are?$"
	.string "But first uh.\n"
	.string "Choose your player character$"

gText_Birch_BoyOrGirl::
	.string "Are you a Groudon?\n"
	.string "Or are you a Groudon?$"

gText_Birch_WhatsYourName::
	@ .string "All right.\n"
	@ .string "What's your name?$"
	.string "Ok swag\n"
	.string "Now put an obligatory name ig$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	@ .string "Ah, okay!\p"
	@ .string "You're {PLAYER}{KUN} who's moving to my\n"
	@ .string "hometown of LITTLEROOT.\l"
	@ .string "I get it now!\p"
	.string "Ok cool swag epic\p"
	.string "$"

gText_Birch_AreYouReady::
	@ .string "All right, are you ready?\p"
	@ .string "Your very own adventure is about\n"
	@ .string "to unfold.\p"
	@ .string "Take courage, and leap into the\n"
	@ .string "world of POKéMON where dreams,\l"
	@ .string "adventure, and friendships await!\p"
	@ .string "Well, I'll be expecting you later.\n"
	@ .string "Come see me in my POKéMON LAB.\p"
	.string "Have fun in the demo TWO\p"
	.string "$"
