gText_Birch_Welcome:: @ 82C897B
	.string "Hello welcome to pokemon bubber epic\n"
	.string "special demo\p"
	.string "$"
	@ .string "Hi! Sorry to keep you waiting!\p"
	@ .string "Welcome to the world of POKéMON!\p"
	@ .string "My name is BIRCH.\p"
	@ .string "But everyone calls me the POKéMON\n"
	@ .string "PROFESSOR.\p"
	@ .string "$"

gText_Birch_Pokemon:: @ 82C89FB
	@ .string "This is what we call a “POKéMON.”\p"
	.string "Take a look at this fucking duck\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "Domohead: finally you let me out of this\n"
	.string "ball holy shit is it hard to breathe in\l"
	.string "there\p"
	.string "Anyway so to recap the duckpets\n"
	.string "hit duckbot666 on the head so hard\l"
	.string "that it flew back to the timeline it\l"
	.string "came from\p"
	.string "Now you'll be controlling the ducks\n"
	.string "as they fuck up the christmas ducks\p"
	.string "$"
	@ .string "This world is widely inhabited by\n"
	@ .string "creatures known as POKéMON.\p"
	@ .string "We humans live alongside POKéMON,\n"
	@ .string "at times as friendly playmates, and\l"
	@ .string "at times as cooperative workmates.\p"
	@ .string "And sometimes, we band together\n"
	@ .string "and battle others like us.\p"
	@ .string "But despite our closeness, we don't\n"
	@ .string "know everything about POKéMON.\p"
	@ .string "In fact, there are many, many\n"
	@ .string "secrets surrounding POKéMON.\p"
	@ .string "To unravel POKéMON mysteries,\n"
	@ .string "I've been undertaking research.\l"
	@ .string "That's what I do.\p"
	@ .string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	@ .string "And you are?$"
	.string "But first choose yo fuckan trainer\p"
	.string "$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	@ .string "All right.\n"
	@ .string "What's your name?$"
	.string "Ok swag\n"
	.string "Now put a name$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	@ .string "Ah, okay!\p"
	@ .string "You're {PLAYER}{KUN} who's moving to my\n"
	@ .string "hometown of LITTLEROOT.\l"
	@ .string "I get it now!\p"
	.string "Ok cool swag epic\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	@ .string "All right, are you ready?\p"
	@ .string "Your very own adventure is about\n"
	@ .string "to unfold.\p"
	@ .string "Take courage, and leap into the\n"
	@ .string "world of POKéMON where dreams,\l"
	@ .string "adventure, and friendships await!\p"
	@ .string "Well, I'll be expecting you later.\n"
	@ .string "Come see me in my POKéMON LAB.\p"
	.string "Have fun in the demo\p"
	.string "$"
