DemoEndRoom_MapScripts::
	.byte 0

DemoEndRoom_EventScript_EndSign::
	msgbox DemoEndSign_Text_0, MSGBOX_SIGN
	end


DemoEndSign_Text_0:
	.string "A non-canon message from Domohead:\n"
	.string "(well, this demo is only semi-canon to\l"
	.string "ccc, i'm not sure where the player fits\l"
	.string "in, since it should just be the duck\l"
	.string "teams fighting...) (also not sure about\l"
	.string "this magic secret room... but anyway...)\l"
	.string "Thank you for playing this special demo\l"
	.string "for Pokemon Bubber! This demo was made\l"
	.string "as an opportunity to show some of the\l"
	.string "stuff we've been working on for the\l"
	.string "game, as well as adding content to the\l"
	.string "CCC, and to rep Pokemon Bubber in the\l"
	.string "5th Anniversary Festival! We'd\l"
	.string "appreciate if you left some feedback\l"
	.string "on the demo in Duck World. Feel free to\l"
	.string "report any bugs that may exist, or\l"
	.string "leave ideas for the game! There's no\l"
	.string "nutshack ARG video for beating this\l"
	.string "demo, however if you do show me that\l"
	.string "you've beaten this demo, I hear you\l"
	.string "might get a special role, or even a\l"
	.string "special DuckPet item... Big thanks to\l"
	.string "the whole Pokemon Bubber team who\l"
	.string "helped make this possible, and I hope\l"
	.string "you look forward to the full game... if\l"
	.string "and when it ever comes, anyway.\p"
	.string "Current Pokemon Bubber Team:\n"
	.string "Domohead: Art, mechanics, organizing\l"
	.string "TheScreenGamerG: Art\l"
	.string "Omasunner: Art\l"
	.string "popdoo323: Art\l"
	.string "hula ellipse: Art, music\l"
	.string "Flame: Art, and programming this whole\l"
	.string "dang thing!\p"
	.string "Special thanks to the former team\n"
	.string "members Elle, fluffyhoneybug, Buggsy,\l"
	.string "and Albinary.... And of course,\l"
	.string "thank you for playing!$"
