DemoEndRoom_MapScripts::
	.byte 0

DemoEndRoom_EventScript_EndSign::
	msgbox DemoEndSign_Text_0, MSGBOX_SIGN
	end


DemoEndSign_Text_0:
	.string "You got...\n"
	.string "...access to the locale space above!\l"
	.string "And that's it!\l"
	.string "maybe speed has some other prize\l"
	.string "for this space idk i'm not\l"
	.string "in charge of the balancing lmao\p"
	.string "Current Pokemon Bubber Team:\n"
	.string "Domohead: Art, organizing, plot\l"
	.string "TheScreenGamerG: Art\l"
	.string "Omasumi: Art\l"
	.string "PandaWithPixels: Art\l"
	.string "popdoo323: Art\l"
	.string "Flame: Art, and programming this whole\l"
	.string "dang thing!\p"
	.string "...maybe even you reading\n"
	.string "this could join the team?\l"
	.string "Thank you for playing!\l"
	.string "Now get on with it.$"

